### ISSUE TITLE
Refresh Boards hangs on Fetching Devices

### ISSUE THREAD

**Issue by keithind** [ryancog/ProffieConfig#3] opened 2024-10-01 22:09 UTC
Hello, I'm not sure what is happening. On two machines, MacBook Pro M1 (Ventura) and MacPro 2019 Intel (Sonoma). Most of the time when I press "Refresh Boards"  when a proffieboard is connected the Device Update dialog displays "Fetching Devices..." and hangs with a small amount of progress in the progress bar which never moves. The proffieboard shows up under the system information app but proffieconfig 1.6.9 on the MacBook Pro and 1.6.10 on the Mac Pro behaves as described above. Once in two days a single proffieboard loaded on the Mac Pro and I was able to program the board. I've disconnected and reconnected the boards. Reset the boards. Force quit and reopened the software. Restarted the computer. I can't get this to work reliably. I think this is probably a me issue, but if you have any insights they would be very appreciated. Thank you.

**Comment by ryancog** [comment] 2024-10-01 22:18
Hmm, no I don't think that's a you issue, that sounds like a proper bug to me. Most people using ProffieConfig have been on Windows, however there was one other person who used it on macOS who had an issue that sounds similar... it was a fluke for them though and it didn't happen again. This sounds far more persistent, but it could be the same issue and just for some reason on your computers it's more pronounced.

The "why" would be the bigger question though, of course.

You said that whenever you press the refresh button, it hangs whenever a Proffieboard is connected. Does it hang when a Proffieboard is *not* connected? If so, is it as the same frequency?

**Comment by keithind** [comment] 2024-10-01 22:45
When no board is connected the dialog displays for a moment, shows fetching devices, small amount of progress and the dialog dismisses itself and I'm back to a responsive functional app interface. I have had no issues when a board is not connected.

**Comment by ryancog** [comment] 2024-10-01 22:47
Ok, give me a second to take a look through things and see if I can come up with plausible points of failure... and then see if I can't recreate them :)

Will let you know once I make progress and/or if there's any more information that might help.

**Comment by keithind** [comment] 2024-10-01 22:48
Thank you. You have an amazing app here and I totally love it when it works.

**Comment by ryancog** [comment] 2024-10-01 22:49
Oh: is it just a particular board that the issue happens with or does it happen with multiple? (Assuming you have multiple, if not that's fine)

**Comment by keithind** [comment] 2024-10-01 22:56
Multiple boards. V2.2, V1.5 and V3.9. I have several of each, except for the 1.5. Is it possible there is some Mac security setting I am not setting correctly or disabling?

**Comment by ryancog** [comment] 2024-10-01 23:02
Gotcha. No, I don't believe there would be.

**Comment by ryancog** [comment] 2024-10-01 23:08
There is a step of the process I think could potentially be a culprit, though I'm not 100% sure. I'm not sure how familiar/comfortable you would be with going through the steps to get the information for me though:

1. You would need to navigate into the ProffieConfig app bundle ("Show Package Contents")
2. Inside, find the `Contents/Resources/arduino-cli` folder, and the `arduino-cli` file inside that folder.
3. Pop open "Terminal", drag the `arduino-cli` file into the Terminal window, then type ` board list` after it, and hit enter.
4. Copy everything and paste it here so I can look it over. (Omit your username from the beginning if you don't want that shared, of course)

If you feel comfortable doing that it'd be super helpful to narrow down the potential causes.

**Comment by keithind** [comment] 2024-10-01 23:14
This is what I get:

Last login: Tue Oct  1 08:08:12 on console
XXX@RXXX ~ % /Applications/ProffieConfig.app/Contents/Resources/arduino-cli/arduino-cli board list
Port                            Protocol Type              Board Name       FQBN                                       Core                
/dev/cu.BLTH                    serial   Serial Port (USB) Unknown                                                                         
/dev/cu.Bluetooth-Incoming-Port serial   Serial Port       Unknown                                                                         
/dev/cu.pci-serial22            serial   Serial Port       Unknown                                                                         
/dev/cu.usbmodem205936B136391   serial   Serial Port (USB) Butterfly-L433CC proffieboard:stm32l4:Butterfly-L433CC      proffieboard:stm32l4
                                         Serial Port (USB) Proffieboard     proffieboard:stm32l4:Proffieboard-L433CC   proffieboard:stm32l4
                                         Serial Port (USB) Proffieboard V2  proffieboard:stm32l4:ProffieboardV2-L433CC proffieboard:stm32l4
                                         Serial Port (USB) Proffieboard V3  proffieboard:stm32l4:ProffieboardV3-L452RE proffieboard:stm32l4



A new release of Arduino CLI is available: 0.34.2 → 1.0.4
https://arduino.github.io/arduino-cli/latest/installation/#latest-packages

**Comment by keithind** [comment] 2024-10-01 23:16
Here is the output with no board connected:

Last login: Tue Oct  1 16:11:36 on ttys000
XXX@RXXX ~ % /Applications/ProffieConfig.app/Contents/Resources/arduino-cli/arduino-cli board list
Port                            Protocol Type              Board Name FQBN Core
/dev/cu.BLTH                    serial   Serial Port (USB) Unknown             
/dev/cu.Bluetooth-Incoming-Port serial   Serial Port       Unknown             
/dev/cu.pci-serial22            serial   Serial Port       Unknown

**Comment by ryancog** [comment] 2024-10-02 04:35
Whenever you get a chance, please try out the [new prerelease](https://github.com/ryancog/ProffieConfig/releases/tag/v1.6.11-rc1) and see if that solves your issue. 

It's somewhat of a shot in the dark, so it's possible there's no difference, but it should at least narrow down possibilities.

**Comment by keithind** [comment] 2024-10-02 04:51
The first board I tried V2.2 board loaded right away and I was able to select the board, but when selected the "Apply Selected Configuration to Board" button stays disabled like no board was selected. Same thing happens wih 1.5 board as well. They do both load. The interface acts as if no board is selected. Thank you so much for jumping on this right away. I super appreciate it.

**Comment by ryancog** [comment] 2024-10-02 06:49
Of course!

Yep, it staying disabled was me having messed something up. I went back and fixed that (and as a bonus made the drop-downs prettier/more in line with modern macOS UI), and did some extra work so the board reboot to boot loader mode for upload/application should be more reliable as well.

Assuming the refresh fix is still working and no more gremlins have popped up, you should be good to go with this new version. [Test it out](https://github.com/ryancog/ProffieConfig/releases/tag/v1.6.11-rc2) and let me know if everything's working as expected. :)

**Comment by ryancog** [comment] 2024-10-02 21:57
Awesome! Glad to hear it's working for you now!

As for that V1.5 board, most commonly whenever that error occurs it's due to one of 3 things:
- Some other software is interfering
- Drivers are not set up correctly (or were overwritten)
- The board took too long to reboot/failed to reboot into boot loader mode

Since the V2 and V3 boards worked, we can effectively rule out the former two likely causes (as those would affect all 3). Why some boards take longer to reboot or just refuse to sometimes I'm not quite sure, but the most reliable way to coerce that to work is to just manually trigger boot loader mode and try again.

Given you have a few boards I assume you know how to trigger boot loader mode already, but in case not, you can either:
- Press and hold the `BOOT` button on the board while either pressing `RESET` or removing and reapplying power.
- Select the board in the drop-down in ProffieConfig, and open the Serial Monitor. Type `RebootDFU` and hit enter. The Serial Monitor should close, and the board should reboot. 

From there if you refresh the boards again, you should see a `BOOTLOADER` entry in the list. Applying the configuration on that entry should virtually always work.

The nice thing about macOS (Window doesn't do this) is that it'll actually show unique `BOOTLOADER` entries in that list when you refresh. On Windows people just have to select an always-visible `BOOTLOADER RECOVERY` entry and hope for the best that the board is actually running in boot loader mode.

**Comment by keithind** [comment] 2024-10-03 02:32
Hello again Still stuck with the V1.5 board. I did know about the "boot" button. I did not know about the Serial Monitor. RebootDFU was ignored ("Whut? :RebootDFU"). The output keeps repeating:
"Amplifier off.

Battery voltage: 0.23

Battery low beep"

The "Reset" command worked, but then right back to the same loop. I think the loop is interrupting the upload, but I can't figure out how to stop it. Thank you again for all of your help. If you don't have time to help me with this crazy it's totally cool. You've done more already than I could possibly have hoped for. Thank you.

**Comment by ryancog** [comment] 2024-10-03 03:43
> I did not know about the Serial Monitor. RebootDFU was ignored ("Whut? :RebootDFU") 

Sometimes the first command you send doesn't go through quite right. Sending it again (and hitting enter a couple times to clear things out) helps. It's been a todo for me to make sure everything is flushed better, but I've not reworked that yet. 

The reset command you mention will restart the board, but it will restart to ProffieOS, not bootloader mode, so it puts you right back to the same place. 

The boot button on the board is hard to hit, so you might not be actually pressing it down and that's causing it to not enter bootloader mode properly. 

Take a look and see if you can't get the RebootDFU command to work with a second try, or by using the BOOT and RESET buttons onboard. If you get the board into bootloader mode and see it in the drop down and it still doesn't take let me know, because that would then definitely be something I should look at :)

And of course, I'm more than happy to help. Tackling problems is (at least) half the fun! I also want to thank you for being helpful in your own right providing detailed explanations of where things are falling short, that's incredibly helpful and very appreciated.

**Comment by keithind** [comment] 2024-10-04 23:57
With the updates you made I have been able to update all but the v1.5 board. Many serial commands work in serial monitor, RebootDFU does not. Even with the button press', hold boot, press and release reset, release boot, I do not see any bootloader entries in the list. Actually until I press reset and have the proffie OS restart the board seems unresponsive. The version command does work and this is what is displayed, "$Id: lightsaber.ino,v 1.279 2018/08/22 03:44:52 hubbe Exp $". Looks like a pretty old version to me. I don't know if that's why it is not playing nice. 

I did already put the configuration I assembled on a different board (a V3.9) for my install. I should probably just let it go, but I'd hate to waste a board. Any thoughts? Feel free to say it's a stupid board, just use a different one. 

BTW, I must say, I love ProffieConfig. It is an amazing tool. Thank you.

**Comment by ryancog** [comment] 2024-10-05 00:15
Hmm... I've never seen `version` output something like that before. I'm admittedly relatively new to Proffie though (I wasn't around during the time of the v1.5 and prior). My first thought is that in an older ProffieOS (TeensyOS even?) `RebootDFU` doesn't exist, and maybe things on the v1.5 work a bit differently also.

Given my lack of experience with that board, I would say to open up a thread on [The Crucible](https://crucible.hubbe.net/) and see what Fredrik has to say. Chances are he knows more about it than me and can give some better insight about what the expected behavior would be.

**Comment by keithind** [comment] 2024-10-05 00:22
I started with Plecter and NEC boards. I picked up this V1.5 when they first came out and never installed it. I will head that direction and see if I can bring this board to life. Thanks again.

**Comment by ryancog** [comment] 2024-10-05 03:26
> BTW, I must say, I love ProffieConfig. It is an amazing tool. Thank you.

Also, I've been kind of ignoring you with these comments :sweat_smile:, but they've not gone unnoticed. I really appreciate the kind words, your support, and how clear and thorough you've been when responding.

I'm thrilled that the tool has been working (mostly) well for you, and that it's been helpful. 

Once I do some polish things I'll do a proper release with those fixes, and close this issue, but I'll keep watch over on the Crucible for your post and see if there ends up being anything useful I can provide in that exchange. :)

Thanks again for reporting this issue. Like I said, there's not too many people on macOS so sometimes bugs like that go unnoticed.

**Comment by ryancog** [comment] 2024-10-05 16:38
Fixed in v1.6.11

**Closed by ryancog** 2024-10-05 16:38 UTC
